⚠️ CONFLICT! Lineage pull request for: skeleton
cisagov/skeleton-aws-lambda-python pull request #34
Opened 2024-09-25 08:31 UTC by cisagovbot

# Lineage Pull Request: CONFLICT #

<img align="left" alt="Achtung!!!" width="100" src="https://raw.githubusercontent.com/cisagov/action-lineage/develop/src/achtung.gif">

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/skeleton-aws-lambda-python.git skeleton-aws-lambda-python
    cd skeleton-aws-lambda-python
    git remote add skeleton https://github.com/cisagov/skeleton-generic.git
    git remote set-url --push skeleton no_push
    git switch develop
    git switch --create lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/workflows/build.yml 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may *append* to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Confirm each item in the "Pre-approval checklist" below.

1. Remove any of the checklist items that do not apply.

1. Ensure every remaining checkbox has been checked.

1. Mark this draft pull request "Ready for review".

## ✅ Pre-approval checklist ##

Remove any of the following that do not apply. If you're unsure about
any of these, don't hesitate to ask. We're here to help!

- [ ] ✌️ The conflicts in this pull request have been resolved.
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

Remove any of the following that do not apply. These boxes should
remain unchecked until the pull request has been approved.

- [ ] Bump major, minor, patch, or pre-release version [as
      appropriate](https://semver.org/#semantic-versioning-specification-semver)
      via the `bump_version.sh` script *if* this repository is
      versioned *and* the changes in this PR [warrant a version
      bump](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api).
- [ ] Finalize version.

## ✅ Post-merge checklist ##

Remove any of the following that do not apply.

- [ ] Create a release.

---

> [!NOTE]
> You are seeing this because one of this repository's maintainers has
> configured [Lineage] to open pull requests.

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2024-09-25 14:19 UTC, dv4harr10 approved these changes

2024-09-25 19:42 UTC, dav3r approved these changes

2024-10-01 14:48 UTC, dv4harr10 commented
Hi Team @all , I think docker-compose.yml line 2 should use double quotes instead of single quotes.

2024-10-01 14:59 UTC, jsf9k commented
> Hi Team @ALL , I think docker-compose.yml line 2 should use double quotes instead of single quotes.

That line is going away anyway.  (The `version` key [has been deprecated](https://docs.docker.com/reference/compose-file/version-and-name/).)  See #31.

2025-05-13 13:49 UTC, jsf9k approved these changes

2025-05-13 19:40 UTC, dv4harr10 approved these changes

2025-05-14 18:20 UTC, dav3r approved these changes
👍

2025-05-27 18:01 UTC, dav3r approved these changes

2025-10-07 17:56 UTC, jsf9k approved these changes

2025-10-07 18:02 UTC, dav3r approved these changes

2025-10-08 07:15 UTC, mcdonnnj requested changes

2025-10-08 07:15 UTC, mcdonnnj commented on .github/labeler.yml
> +          - tests/*.py
I think any files changed in the `tests/` sub-directory should result in the `test` label being applied.

```suggestion
          - tests/**
```

2025-10-08 07:15 UTC, mcdonnnj commented on tests/test_version.py
Changing the format of `src/version.txt` breaks the `test_release_version` test because it will try to `exec()` a text file now. You could pull the[ fixture in `cisagov/skeleton-docker`](https://github.com/cisagov/skeleton-docker/blob/722507bd51e06538f1f85b659df616ca7ca7fcbd/tests/conftest.py#L41-L46) and mirror the [same test there](https://github.com/cisagov/skeleton-docker/blob/722507bd51e06538f1f85b659df616ca7ca7fcbd/tests/container_test.py#L61-L68).

2025-10-08 14:37 UTC, jsf9k commented on tests/test_version.py
Do you prefer that or would you prefer that I revert the format change?

2025-10-08 15:28 UTC, mcdonnnj commented on tests/test_version.py
I would prefer updating the test since we do not use the version file in actual Python code. Using Python code inside of the version file is just a holdover from the old `bump_version.sh` script.

2025-10-08 16:36 UTC, jsf9k commented on tests/test_version.py
Please see commit fead28f.

2025-10-08 20:06 UTC, mcdonnnj commented on tests/test_version.py
> +@pytest.fixture(scope="session")
Nitpick but please move this fixture into `conftest.py` since it is a session fixture.

2025-10-09 12:59 UTC, jsf9k commented on tests/test_version.py
> +@pytest.fixture(scope="session")
Please see commit b1b3495.

2025-10-09 19:41 UTC, jsf9k commented on setup-env
> +  local prerelease+="(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)"
This change should be made in [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic), if we want to make it at all.  Our shebang does explicitly mention `bash`, so I don't think we care about cross-shell compatibility here.

2025-10-09 19:41 UTC, jsf9k commented on setup-env
> +  local prerelease+=")?"
This change should be made in [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic), if we want to make it at all.  Our shebang does explicitly mention `bash`, so I don't think we care about cross-shell compatibility here.

2025-10-09 19:41 UTC, jsf9k commented on setup-env
> +  local prerelease+=")?"
This change should be made in [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic), if we want to make it at all.  Our shebang does explicitly mention `bash`, so I don't think we care about cross-shell compatibility here.

2025-10-09 19:56 UTC, mcdonnnj approved these changes

2025-10-09 20:13 UTC, merged